version: 2.1

executors:
  esplinux-bootstrap:
    docker:
      - image: esplinux/bootstrap
    working_directory: ~/
    environment:
      VERSION: "0.01"

  musl:
    executor: esplinux-bootstrap
    steps:
      - run: esp add ghr espbuild
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: |
            espbuild musl.conf
            ghr $GHR_FLAGS -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package

workflows:
  build:
    jobs:
      - musl
